ALTER TABLE campaigns
  ADD COLUMN IF NOT EXISTS category VARCHAR(100),
  ADD COLUMN IF NOT EXISTS goal_amount_usd NUMERIC(20,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS creator_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS creator_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS creator_org VARCHAR(255),
  ADD COLUMN IF NOT EXISTS creator_country VARCHAR(120),
  ADD COLUMN IF NOT EXISTS creator_bio TEXT,
  ADD COLUMN IF NOT EXISTS document_file_names TEXT[] DEFAULT '{}'::TEXT[];

ALTER TABLE milestones
  ADD COLUMN IF NOT EXISTS name VARCHAR(255) DEFAULT 'Milestone',
  ADD COLUMN IF NOT EXISTS amount_usd NUMERIC(20,2) DEFAULT 0;
